# Generated by Django 2.2.5 on 2021-07-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210723_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avtar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
